apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: app-two
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: app-two-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>App 2</title>
      <style>
        body {
          background-color: #5bc0de;
          font-family: Arial, sans-serif;
          text-align: center;
          padding-top: 100px;
          color: white;
        }
        h1 {
          font-size: 72px;
        }
      </style>
    </head>
    <body>
      <h1>Welcome to App 2</h1>
      <p>You accessed this app using the app2.com host header</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  selector:
    app: app-two
  ports:
  - port: 80
    targetPort: 80
