Vagrant.configure("2") do |config|
  # Configure SSH for all machines
  config.ssh.insert_key = true
  config.ssh.forward_agent = true

  # Define the machine: afatirS (Server)
  config.vm.define "afatirS" do |vm1|
    vm1.vm.box = "debian/bookworm64"
    vm1.vm.hostname = "afatirS"
    # Configure dedicated IP on eth1
    vm1.vm.network "private_network", ip: "192.168.56.110"
    
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "afatirS"
    end

    # Provision K3s server (controller mode)
    vm1.vm.provision "shell", path: "./scripts/server_setup.sh"
    
    # Deploy the web applications automatically
    vm1.vm.provision "shell", path: "./scripts/setup_apps.sh"
  end
end
