Vagrant.configure("2") do |config|
  # Configure SSH for all machines
  config.ssh.insert_key = true
  config.ssh.forward_agent = true

  # Define the first machine: afatirS (Server)
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "debian/bookworm64"
    vm1.vm.hostname = "afatirS"
    # Configure dedicated IP on eth1
    vm1.vm.network "private_network", ip: "192.168.56.110"
    
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "afatir"
    end
    
    # Provision K3s server (controller mode)
    vm1.vm.provision "shell", path: "./scripts/server_setup.sh"
  end
  
  # Define the second machine: afatirSW (ServerWorker)
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "debian/bookworm64"
    vm2.vm.hostname = "afatirSW"
    # Configure dedicated IP on eth1
    vm2.vm.network "private_network", ip: "192.168.56.111"
    
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "afatir"
    end
    
    # Provision K3s agent
    vm2.vm.provision "shell", path: "./scripts/agent_setup.sh"
  end
end
